//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XmlRW.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class FLOW_ONSIPDET
    {
        public int ID { get; set; }
        public string INS_ID { get; set; }
        public string STOK_KOD { get; set; }
        public Nullable<decimal> MIKTAR { get; set; }
        public Nullable<int> OBR { get; set; }
        public Nullable<decimal> FIYAT { get; set; }
        public Nullable<int> DOVIZTIP { get; set; }
        public string DEPO_KOD { get; set; }
        public string SIPNO { get; set; }
        public string ACIKLAMA { get; set; }
        public Nullable<decimal> SATISK { get; set; }
        public Nullable<decimal> TESLIM_MIKTAR { get; set; }
        public string AKTIF { get; set; }
        public string FISNO { get; set; }
        public string MAGAZA { get; set; }
        public string MARKA { get; set; }
        public string SATICI { get; set; }
        public Nullable<decimal> BFIYAT { get; set; }
        public string KALEMNOTU { get; set; }
        public string TURKCENOT { get; set; }
    }
}
