//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XmlRW.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class FLOW_ONSIPMAS
    {
        public int ID { get; set; }
        public string FISNO { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public string OZELKOD { get; set; }
        public string PLASIYER { get; set; }
        public string CARI { get; set; }
        public string KAYITYAPAN { get; set; }
        public Nullable<System.DateTime> KAYITTARIHI { get; set; }
        public string INS_ID { get; set; }
        public string AKTIF { get; set; }
        public string TIPI { get; set; }
        public string EXPORTREFNO { get; set; }
        public string EXPORTTYPE { get; set; }
        public Nullable<decimal> GENISK { get; set; }
        public string REVIZEINSID { get; set; }
        public string KAYIT_DURUMU { get; set; }
        public string SIRKET { get; set; }
        public Nullable<System.DateTime> TERMINTARIHI { get; set; }
        public string SEVKTIPI { get; set; }
        public Nullable<System.DateTime> FABRIKACIKIS { get; set; }
        public string KACINCISIPARIS { get; set; }
        public string MUSTERIADI { get; set; }
        public string GURMENFISNO { get; set; }
    }
}
