//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XmlRW.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class FLOW_FISNORES
    {
        public int ID { get; set; }
        public string FATIRSNO { get; set; }
        public string TIPI { get; set; }
    }
}
