//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XmlRW.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GURMENPVCEntities : DbContext
    {
        public GURMENPVCEntities()
            : base("name=GURMENPVCEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FLOW_ONSIPMAS> FLOW_ONSIPMAS { get; set; }
        public virtual DbSet<FLOW_FISNORES> FLOW_FISNORES { get; set; }
        public virtual DbSet<TBLSTSABIT> TBLSTSABIT { get; set; }
        public virtual DbSet<FLOW_ONSIPDET> FLOW_ONSIPDET { get; set; }
    }
}
