//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XmlRW.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLSTSABIT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLSTSABIT()
        {
            this.TBLSTSABIT1 = new HashSet<TBLSTSABIT>();
        }
    
        public short SUBE_KODU { get; set; }
        public short ISLETME_KODU { get; set; }
        public string STOK_KODU { get; set; }
        public string URETICI_KODU { get; set; }
        public string STOK_ADI { get; set; }
        public string GRUP_KODU { get; set; }
        public string KOD_1 { get; set; }
        public string KOD_2 { get; set; }
        public string KOD_3 { get; set; }
        public string KOD_4 { get; set; }
        public string KOD_5 { get; set; }
        public string SATICI_KODU { get; set; }
        public string OLCU_BR1 { get; set; }
        public string OLCU_BR2 { get; set; }
        public Nullable<decimal> PAY_1 { get; set; }
        public Nullable<decimal> PAYDA_1 { get; set; }
        public string OLCU_BR3 { get; set; }
        public Nullable<decimal> PAY2 { get; set; }
        public Nullable<decimal> PAYDA2 { get; set; }
        public string FIAT_BIRIMI { get; set; }
        public Nullable<decimal> AZAMI_STOK { get; set; }
        public Nullable<decimal> ASGARI_STOK { get; set; }
        public Nullable<decimal> TEMIN_SURESI { get; set; }
        public Nullable<decimal> KUL_MIK { get; set; }
        public Nullable<short> RISK_SURESI { get; set; }
        public string ZAMAN_BIRIMI { get; set; }
        public Nullable<decimal> SATIS_FIAT1 { get; set; }
        public Nullable<decimal> SATIS_FIAT2 { get; set; }
        public Nullable<decimal> SATIS_FIAT3 { get; set; }
        public Nullable<decimal> SATIS_FIAT4 { get; set; }
        public Nullable<byte> SAT_DOV_TIP { get; set; }
        public Nullable<decimal> DOV_ALIS_FIAT { get; set; }
        public Nullable<decimal> DOV_MAL_FIAT { get; set; }
        public Nullable<decimal> DOV_SATIS_FIAT { get; set; }
        public Nullable<int> MUH_DETAYKODU { get; set; }
        public Nullable<decimal> BIRIM_AGIRLIK { get; set; }
        public Nullable<decimal> NAKLIYET_TUT { get; set; }
        public Nullable<decimal> KDV_ORANI { get; set; }
        public Nullable<byte> ALIS_DOV_TIP { get; set; }
        public Nullable<short> DEPO_KODU { get; set; }
        public Nullable<byte> DOV_TUR { get; set; }
        public Nullable<byte> URET_OLCU_BR { get; set; }
        public string BILESENMI { get; set; }
        public string MAMULMU { get; set; }
        public Nullable<decimal> FORMUL_TOPLAMI { get; set; }
        public string UPDATE_KODU { get; set; }
        public Nullable<decimal> MAX_ISKONTO { get; set; }
        public Nullable<decimal> ECZACI_KARI { get; set; }
        public Nullable<decimal> MIKTAR { get; set; }
        public Nullable<decimal> MAL_FAZLASI { get; set; }
        public Nullable<decimal> KDV_TENZIL_ORAN { get; set; }
        public string KILIT { get; set; }
        public string ONCEKI_KOD { get; set; }
        public string SONRAKI_KOD { get; set; }
        public string BARKOD1 { get; set; }
        public string BARKOD2 { get; set; }
        public string BARKOD3 { get; set; }
        public Nullable<decimal> ALIS_KDV_KODU { get; set; }
        public Nullable<decimal> ALIS_FIAT1 { get; set; }
        public Nullable<decimal> ALIS_FIAT2 { get; set; }
        public Nullable<decimal> ALIS_FIAT3 { get; set; }
        public Nullable<decimal> ALIS_FIAT4 { get; set; }
        public Nullable<decimal> LOT_SIZE { get; set; }
        public Nullable<decimal> MIN_SIP_MIKTAR { get; set; }
        public Nullable<short> SABIT_SIP_ARALIK { get; set; }
        public string SIP_POLITIKASI { get; set; }
        public Nullable<byte> OZELLIK_KODU1 { get; set; }
        public Nullable<byte> OZELLIK_KODU2 { get; set; }
        public Nullable<byte> OZELLIK_KODU3 { get; set; }
        public Nullable<byte> OZELLIK_KODU4 { get; set; }
        public Nullable<byte> OZELLIK_KODU5 { get; set; }
        public Nullable<byte> OPSIYON_KODU1 { get; set; }
        public Nullable<byte> OPSIYON_KODU2 { get; set; }
        public Nullable<byte> OPSIYON_KODU3 { get; set; }
        public Nullable<byte> OPSIYON_KODU4 { get; set; }
        public Nullable<byte> OPSIYON_KODU5 { get; set; }
        public Nullable<byte> BILESEN_OP_KODU { get; set; }
        public Nullable<decimal> SIP_VER_MAL { get; set; }
        public Nullable<decimal> ELDE_BUL_MAL { get; set; }
        public Nullable<decimal> YIL_TAH_KUL_MIK { get; set; }
        public Nullable<decimal> EKON_SIP_MIKTAR { get; set; }
        public string ESKI_RECETE { get; set; }
        public string OTOMATIK_URETIM { get; set; }
        public string ALFKOD { get; set; }
        public string SAFKOD { get; set; }
        public string KODTURU { get; set; }
        public string S_YEDEK1 { get; set; }
        public string S_YEDEK2 { get; set; }
        public Nullable<decimal> F_YEDEK3 { get; set; }
        public Nullable<decimal> F_YEDEK4 { get; set; }
        public string C_YEDEK5 { get; set; }
        public string C_YEDEK6 { get; set; }
        public Nullable<byte> B_YEDEK7 { get; set; }
        public Nullable<short> I_YEDEK8 { get; set; }
        public Nullable<int> L_YEDEK9 { get; set; }
        public Nullable<System.DateTime> D_YEDEK10 { get; set; }
        public string GIRIS_SERI { get; set; }
        public string CIKIS_SERI { get; set; }
        public string SERI_BAK { get; set; }
        public string SERI_MIK { get; set; }
        public string SERI_GIR_OT { get; set; }
        public string SERI_CIK_OT { get; set; }
        public string SERI_BASLANGIC { get; set; }
        public string FIYATKODU { get; set; }
        public Nullable<int> FIYATSIRASI { get; set; }
        public string PLANLANACAK { get; set; }
        public Nullable<decimal> LOT_SIZECUSTOMER { get; set; }
        public Nullable<decimal> MIN_SIP_MIKTARCUSTOMER { get; set; }
        public string GUMRUKTARIFEKODU { get; set; }
        public string ABCKODU { get; set; }
        public string PERFORMANSKODU { get; set; }
        public string SATICISIPKILIT { get; set; }
        public string MUSTERISIPKILIT { get; set; }
        public string SATINALMAKILIT { get; set; }
        public string SATISKILIT { get; set; }
        public Nullable<decimal> EN { get; set; }
        public Nullable<decimal> BOY { get; set; }
        public Nullable<decimal> GENISLIK { get; set; }
        public string SIPLIMITVAR { get; set; }
        public string SONSTOKKODU { get; set; }
        public string ONAYTIPI { get; set; }
        public Nullable<int> ONAYNUM { get; set; }
        public string FIKTIF_MAM { get; set; }
        public string YAPILANDIR { get; set; }
        public string SBOMVARMI { get; set; }
        public string BAGLISTOKKOD { get; set; }
        public string YAPKOD { get; set; }
        public string ALISTALTEKKILIT { get; set; }
        public string SATISTALTEKKILIT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLSTSABIT> TBLSTSABIT1 { get; set; }
        public virtual TBLSTSABIT TBLSTSABIT2 { get; set; }
    }
}
